import { Hono } from 'hono';
import { getCookie, setCookie, deleteCookie } from 'hono/cookie';
import * as oauth from 'oauth4webapi';

type Env = { DB: D1Database; ASSETS: Fetcher; OIDC_ISSUER: string; OIDC_CLIENT_ID?: string; OIDC_CLIENT_SECRET?: string; OIDC_REDIRECT_URI?: string; GEMINI_API_KEY?: string; GEMINI_MODEL: string };
const app = new Hono<{ Bindings: Env }>();
const categories = ['無線電規章與相關法規','無線電通訊方法','無線電系統原理','無線電相關安全防護','電磁相容性技術','射頻干擾的預防與排除'];
const json = (c: any, data: unknown, status = 200) => c.json(data, status);
const sid = (c: any) => getCookie(c, 'arl_session');
async function user(c: any) { const id = sid(c); if (!id) return null; return (await c.env.DB.prepare('SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.id=? AND s.expires_at>?').bind(id,new Date().toISOString()).first()) as any; }

app.get('/api/health', c => json(c, { ok: true, categories }));
app.get('/api/me', async c => json(c, { user: await user(c) }));
app.get('/api/login', async c => { if (!c.env.OIDC_CLIENT_ID || !c.env.OIDC_REDIRECT_URI) return json(c,{error:'OIDC 尚未設定'},503); const issuer=new URL(c.env.OIDC_ISSUER); const as=await oauth.processDiscoveryResponse(issuer,await oauth.discoveryRequest(issuer,{algorithm:'oidc'})); const state=oauth.generateRandomState(), nonce=oauth.generateRandomNonce(), verifier=oauth.generateRandomCodeVerifier(); const challenge=await oauth.calculatePKCECodeChallenge(verifier); const tx=crypto.randomUUID(); await c.env.DB.prepare('CREATE TABLE IF NOT EXISTS oidc_transactions (id TEXT PRIMARY KEY,state TEXT,nonce TEXT,verifier TEXT,expires_at TEXT)').run(); await c.env.DB.prepare('INSERT INTO oidc_transactions VALUES (?,?,?,?,?)').bind(tx,state,nonce,verifier,new Date(Date.now()+600000).toISOString()).run(); const u=new URL(as.authorization_endpoint!); Object.entries({client_id:c.env.OIDC_CLIENT_ID,redirect_uri:c.env.OIDC_REDIRECT_URI,response_type:'code',scope:'openid profile email',code_challenge:challenge,code_challenge_method:'S256',state,nonce}).forEach(([k,v])=>u.searchParams.set(k,v)); setCookie(c,'arl_oidc',tx,{httpOnly:true,secure:true,sameSite:'Lax',maxAge:600,path:'/'}); return c.redirect(u.href); });
app.get('/callback', async c => { const txid=getCookie(c,'arl_oidc'), code=c.req.query('code'), state=c.req.query('state'); if(!txid||!code||!state) return c.text('登入資料不完整',400); const tx=await c.env.DB.prepare('SELECT * FROM oidc_transactions WHERE id=? AND expires_at>?').bind(txid,new Date().toISOString()).first<any>(); if(!tx||tx.state!==state) return c.text('登入交易無效或已過期',400); const issuer=new URL(c.env.OIDC_ISSUER), as=await oauth.processDiscoveryResponse(issuer,await oauth.discoveryRequest(issuer,{algorithm:'oidc'})); const client={client_id:c.env.OIDC_CLIENT_ID!,id_token_signed_response_alg:'EdDSA'} as oauth.Client; const params=oauth.validateAuthResponse(as,client,new URL(c.req.url),tx.state); const token=await oauth.authorizationCodeGrantRequest(as,client,c.env.OIDC_CLIENT_SECRET?oauth.ClientSecretPost(c.env.OIDC_CLIENT_SECRET):oauth.None(),params,c.env.OIDC_REDIRECT_URI!,tx.verifier); const tokens=await oauth.processAuthorizationCodeResponse(as,client,token,{expectedNonce:tx.nonce,requireIdToken:true}); const claims=oauth.getValidatedIdTokenClaims(tokens) as any; if(!claims?.sub||!claims?.sid) return c.text('OIDC 身分資料無效',400); const info=await oauth.processUserInfoResponse(as,client,claims.sub,await oauth.userInfoRequest(as,client,tokens.access_token)); const uid=claims.sub as string; await c.env.DB.prepare('INSERT INTO users(id,email,name) VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET email=excluded.email,name=excluded.name,updated_at=CURRENT_TIMESTAMP').bind(uid,(info as any).email??null,(info as any).name??null).run(); const session=crypto.randomUUID(); await c.env.DB.prepare('INSERT INTO sessions(id,user_id,central_sid,expires_at) VALUES(?,?,?,?)').bind(session,uid,claims.sid,new Date(Date.now()+2592000000).toISOString()).run(); deleteCookie(c,'arl_oidc'); setCookie(c,'arl_session',session,{httpOnly:true,secure:true,sameSite:'Lax',maxAge:2592000,path:'/'}); return c.redirect('/'); });
app.post('/api/logout', async c => { const s=sid(c); if(s) await c.env.DB.prepare('DELETE FROM sessions WHERE id=?').bind(s).run(); deleteCookie(c,'arl_session'); return json(c,{ok:true}); });
app.get('/api/questions', async c => { const u=await user(c); if(!u) return json(c,{error:'請先登入'},401); const rows=await c.env.DB.prepare('SELECT id,category,number,prompt,options_json FROM questions WHERE level=3 ORDER BY RANDOM()').all(); return json(c,{questions:rows.results}); });
app.post('/api/check', async c => { const u=await user(c); if(!u) return json(c,{error:'請先登入'},401); const b=await c.req.json<{question_id:string;answer:string}>(); const q=await c.env.DB.prepare('SELECT id,answer,prompt FROM questions WHERE id=?').bind(b.question_id).first<any>(); if(!q) return json(c,{error:'題目不存在'},404); const correct=q.answer===b.answer; if(correct) await c.env.DB.prepare('DELETE FROM wrong_notes WHERE user_id=? AND question_id=?').bind(u.id,q.id).run(); else await c.env.DB.prepare('INSERT INTO wrong_notes(user_id,question_id,note,updated_at) VALUES(?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(user_id,question_id) DO UPDATE SET updated_at=CURRENT_TIMESTAMP').bind(u.id,q.id,'待 AI 分析').run(); return json(c,{correct,answer:q.answer}); });
app.post('/api/exams', async c => { const u=await user(c); if(!u) return json(c,{error:'請先登入'},401); const quotas=[13,13,6,1,1,1]; const picked:any[]=[]; for(let i=0;i<categories.length;i++){const rows=await c.env.DB.prepare('SELECT id,category,number,prompt,options_json FROM questions WHERE level=3 AND category=? ORDER BY RANDOM() LIMIT ?').bind(categories[i],quotas[i]).all(); picked.push(...rows.results)} return json(c,{mode:'exam',duration_seconds:2400,pass_score:25,questions:picked}); });
app.get('/api/wrong-notes', async c => { const u=await user(c); if(!u) return json(c,{error:'請先登入'},401); const rows=await c.env.DB.prepare('SELECT n.*,q.category,q.number,q.prompt,q.options_json FROM wrong_notes n JOIN questions q ON q.id=n.question_id WHERE n.user_id=? ORDER BY n.updated_at DESC').bind(u.id).all(); return json(c,{notes:rows.results}); });
app.post('/api/reset-progress', async c => { const u=await user(c); if(!u) return json(c,{error:'請先登入'},401); await c.env.DB.batch([c.env.DB.prepare('DELETE FROM question_stats WHERE user_id=?').bind(u.id),c.env.DB.prepare('DELETE FROM wrong_notes WHERE user_id=?').bind(u.id),c.env.DB.prepare('DELETE FROM attempts WHERE user_id=?').bind(u.id)]); return json(c,{ok:true}); });
app.post('/api/attempts', async c => { const u=await user(c); if(!u) return json(c,{error:'請先登入'},401); const b=await c.req.json<{mode:string;question_ids:string[];answers:Record<string,string>;started_at:string}>(); const qs=await c.env.DB.prepare(`SELECT id,answer FROM questions WHERE id IN (${b.question_ids.map(()=>'?').join(',')})`).bind(...b.question_ids).all<any>(); let score=0; const wrong:string[]=[]; for(const q of qs.results){const ok=b.answers[q.id]===q.answer; if(ok)score++; else wrong.push(q.id); await c.env.DB.prepare('INSERT INTO question_stats(user_id,question_id,seen_count,correct_count,wrong_count,mastery,last_wrong_at) VALUES(?,?,1,?,?,?,?) ON CONFLICT(user_id,question_id) DO UPDATE SET seen_count=seen_count+1,correct_count=correct_count+excluded.correct_count,wrong_count=wrong_count+excluded.wrong_count,mastery=MIN(1.0,MAX(0.0,mastery+CASE WHEN excluded.correct_count=1 THEN 0.15 ELSE -0.2 END)),last_wrong_at=excluded.last_wrong_at').bind(u.id,q.id,ok?1:0,ok?0:1,ok?1:0,ok?null:new Date().toISOString()).run(); } await c.env.DB.prepare('INSERT INTO attempts(id,user_id,mode,question_ids_json,answers_json,score,passed,started_at,finished_at) VALUES(?,?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),u.id,b.mode,JSON.stringify(b.question_ids),JSON.stringify(b.answers),score,score>=25?1:0,b.started_at,new Date().toISOString()).run(); return json(c,{score,total:b.question_ids.length,passed:score>=25,wrong}); });
app.post('/api/analyze', async c => { const u=await user(c); if(!u) return json(c,{error:'請先登入'},401); if(!c.env.GEMINI_API_KEY) return json(c,{error:'尚未設定 GEMINI_API_KEY'},503); const body=await c.req.json<{question_id:string}>(); const q=await c.env.DB.prepare('SELECT * FROM questions WHERE id=?').bind(body.question_id).first<any>(); if(!q) return json(c,{error:'題目不存在'},404); const endpoint=`https://generativelanguage.googleapis.com/v1beta/models/${c.env.GEMINI_MODEL}:generateContent?key=${c.env.GEMINI_API_KEY}`; const response=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contents:[{parts:[{text:`請用繁體中文分析業餘無線電考題，清楚說明正確答案、各選項錯誤原因、核心知識點與一題重測題。題目：${q.prompt}\n選項：${q.options_json}\n正確答案：${q.answer}`}]}]})}); const result=await response.json<any>(); const summary=result.candidates?.[0]?.content?.parts?.[0]?.text ?? 'AI 暫時沒有回覆'; await c.env.DB.prepare('INSERT INTO ai_analyses(question_id,summary,concepts_json) VALUES(?,?,?) ON CONFLICT(question_id) DO UPDATE SET summary=excluded.summary,analyzed_at=CURRENT_TIMESTAMP').bind(q.id,summary,'[]').run(); return json(c,{summary}); });
app.all('*', async c => c.env.ASSETS.fetch(c.req.raw));
export default app;
